### ISSUE TITLE
Cool...?

### ISSUE THREAD

**Issue by Esinko** [woodwoerk/eira-math-editor#2]
Hi!

This seems like a really great idea! Where did you get the idea from initially?
Also it would be great if the contribution guidelines would be a bit more clear.

**Comment by Esinko** [comment]
Is matikkaeditori.fi related to this project? They look pretty similar...

**Comment by woodwoerk** [comment]
Hey @Esinko!

Thanks for your comment, I'll be updating the contribution guidelines and improving the docs this week. The idea came from [Eira high school](http://www.eira.fi) to build an open source editor that expands upon the features of the [Abitti Rich Text Editor](https://github.com/digabi/rich-text-editor). This is not related to matikkaeditori.fi. Most importantly, this is open source so that other schools can roll out their own versions easily.

**Comment by Esinko** [comment]
Alright! That makes sense.
